# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Marvel' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Marvel

  target 'MarvelTests' do
    inherit! :search_paths
    pod 'lottie-ios'
    pod 'AlamofireImage', '~> 4.1'
    pod 'Alamofire'
  end

  target 'MarvelUITests' do
    # Pods for testing
  end

end
